### ISSUE TITLE
cannot install on windows

### ISSUE THREAD

**Issue by ramstein74** [linemanjs/lineman-less#4] opened 2014-06-29 15:25 UTC
Can you help solve this issue?
Thank you
![image](https://cloud.githubusercontent.com/assets/1210858/3423634/9a128b00-ffa1-11e3-8739-d435899f47b3.png)

**Comment by jayharris** [comment] 2015-04-10 13:38
I am unable to reproduce this issue on node 0.10.x or 0.12.x on either Windows or OSX.

Do you have any further information on this? Debug logs? What version of Lineman are you using? A sample repo that can reproduce the issue may also be helpful.

**Comment by jayharris** [comment] 2015-04-10 13:39
Closing as duplicate of #5

**Closed by jayharris** 2015-04-10 13:39 UTC
